<!DOCTYPE html>
<html>
<head>
<title>Happy Birthday Janie</title>
</head>

<body style="margin:0; text-align:center; font-family:sans-serif; background:linear-gradient(135deg,#ff9a9e,#fad0c4); color:white;">

<h1>🎉 Happy Birthday Janie 🎉</h1>
<h3>Wishing you happiness & smiles 💖</h3>

<div style="font-size:70px;">🎂🕯️🌹🌸</div>

<p style="padding:20px;">
Janie 💫<br><br>
You are truly an amazing person 🌸<br>
Your smile makes everything better ✨<br><br>
Wishing you happiness and success always 💕
</p>

<button onclick="start()">🎶 Tap for Surprise</button>

<audio id="m" src="https://www.bensound.com/bensound-music/bensound-romantic.mp3" loop></audio>

<script>
function start(){
document.getElementById("m").play().catch(()=>{});
alert("💖 Enjoy your special day Janie 💖");
}
</script>

</body>
</html># This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        # https://github.com/ruby/setup-ruby/releases/tag/v1.207.0
        uses: ruby/setup-ruby@4a9ddd6f338a97768b8006bf671dfbad383215f4
        with:
          ruby-version: '3.1' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production
      - name: Upload artifact
        # Automatically uploads an artifact from the './_site' directory by default
        uses: actions/upload-pages-artifact@v3

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
